### PR TITLE
xmrs resize tool

### PR DESCRIPTION
**Pull request by aranciaga**
Might be util for some people. Basically it's xmmv with some changes.

### CODE REVIEW

**Comment by z3bra** [comment]
I realise that you want to help, but this is no excuse to submitting such a low quality pull-request.
This code is not even usable, and has obvious bugs.
If you want to help, then only submit code that is first useful to **YOU** before submitting code for others. I cannot believe that you have tested this code, not even once!

**Comment by aranciaga** [comment]
LOL, this code is yours dude. I only change few lines, also, it's beta. Needs a validation for window size before keep resizing. Cheers.

**Comment by z3bra** [comment]
LOL, you took a working code and turned it into a non-working one. You cannot blame us for that. When I first tried your code, I had no way to terminate it, and it ended up killing my window!

In this case "changing a few lines" rendered the software unusable. And calling it "beta" is no excuse for submitting a PR you didn't even bother testing. If you had run this code at least ONCE, you would have noticed it's not working.

**Comment by lwilletts** [comment]
@rainbowintheshell How in anyway do you think your behaviour here is acceptable to getting code into the project?

**Pull request closed without merging**
